//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bombex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public int ID { get; set; }
        public string ResidentID { get; set; }
        public string ResidentialIDPrimary { get; set; }
        public string RelationshipType { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual Resident Resident { get; set; }
    }
}
