//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bombex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int ID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Movement1 { get; set; }
        public string Comments { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
