//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bombex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Particular
    {
        public int ID { get; set; }
        public string Esipei { get; set; }
        public string WaterMeter { get; set; }
        public string HouseNumber { get; set; }
        public string ResidentID { get; set; }
        public string Comments { get; set; }
    
        public virtual Resident Resident { get; set; }
    }
}
