//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bombex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int SysID { get; set; }
        public string EmpID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Comments { get; set; }
        public string ResidentID { get; set; }
        public string ResidentIDVisitor1 { get; set; }
        public string ResidentIDVisitor2 { get; set; }
        public Nullable<int> UnitNumber { get; set; }
        public Nullable<int> NumberOfFamilyMembers { get; set; }
    
        public virtual Resident Resident { get; set; }
    }
}
