//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bombex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public byte[] Photo { get; set; }
        public string ResidentID { get; set; }
    
        public virtual Resident Resident { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
